### ISSUE TITLE
Color is totally missing on my win 10 console

### ISSUE THREAD

**Issue by jack4it** [serilog/serilog-sinks-literate#13]
I mean no color at all... weird

**Comment by adamchester** [comment]
Hi @jack4it, could it be that something is intercepting the console output and then printing it without colour?

**Comment by nblumhardt** [comment]
I've seen this happen with `dotnet run` - is that being used here?

**Comment by jack4it** [comment]
@nblumhardt Ah, you are right. I double checked, I was running `dotnet watch run ...`. Getting rid of the `watch` part brings the color on. Looks good! and sad about the `watch` command is not forwarding the color info. do you think if it is possible for the `watch` to not throw away the color? Hmm

**Comment by nblumhardt** [comment]
Thanks for the follow-up. I think #9 (including ANSI color codes) should do it. Let's leave this open as a reminder to verify once that's done.

**Comment by nblumhardt** [comment]
#19 covers this.
