### ISSUE TITLE
Support LoggingLevelSwitch?

### ISSUE THREAD

**Issue by frg** [serilog/serilog-sinks-literate#18]
Hi,

Are there any plans to support LoggingLevelSwitch?
Unless I'm missing something, not passing restrictedToMinimumLevel will default to verbose.

Thanks in advance,
Jean

**Comment by nblumhardt** [comment]
Hi @frg - this will include it: https://github.com/serilog/serilog-sinks-console/issues/7

HTH!
Nick

**Comment by nblumhardt** [comment]
#19 will take care of this.
