### ISSUE TITLE
Escaping /n/r after upgrade from 2.0.0 to 3.0.0

### ISSUE THREAD

**Issue by kemsky** [serilog/serilog-sinks-literate#23]
Version 3.0.0 started escaping CRLF symbols effectively removing line breaks, which makes console output pretty useless. 

Is it possible to configure escaping?

**Comment by nblumhardt** [comment]
Thanks for the note; it sounds like you're using a custom `outputTemplate`, or might just need to rebuild: adding `{Message:l}` to the output template should switch this off.

**Comment by kemsky** [comment]
Thanks, it helps.
