### ISSUE TITLE
Ability to direct Error and Fatal to Console.Error instead of Console.Out

### ISSUE THREAD

**Issue by WorldMaker** [serilog/serilog-sinks-literate#6]
It can be useful for many automation reasons to direct Error and Fatal logs to standard error (Console.Error) or its redirection rather than to standard out.

**Comment by nblumhardt** [comment]
Thanks for the suggestion, I agree it's a worthwhile option to add. Do you have any proposal for how the API should look? `errorsToStderr: true` as a configuration arg? Thanks!

**Comment by WorldMaker** [comment]
That API would work for my current needs. I've also seen apps that send all logs to standard error (as they always expect standard output to be redirected), so I'm not sure if that might also be a useful feature to the next developer and maybe someone might want an API more like `minimumLevelToStandardError: LogEventLevel.Error`.

**Comment by nblumhardt** [comment]
`minimumLevelToStandardError` sounds like a good move, thanks for the suggestion. The name of the arg (starting with `m`) might catch people's attention when what they're looking for is `restrictedToMinimumLevel`; perhaps `standardErrorFromLevel:` or `standardErrorFromMinimumLevel:`?

We probably should do this across `Console()` and `ColoredConsole()` as well.

Marking this one as "up-for-grabs". Cheers!

**Comment by nblumhardt** [comment]
Closed in #12.
