### ISSUE TITLE
Color palette poor under Linux on Docker on Windows - Theme Support?

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-sinks-literate#9]
Running the Docker on Windows beta; the dark gray brackets are not visible, blue Booleans and `null` are unreadable, and the overall color scheme is washed out and dull.

![image](https://cloud.githubusercontent.com/assets/342712/17118913/527ae142-5306-11e6-84d5-583ec609061a.png)

Since many terminals have different color capabilities or renderings, and just about every programmer has different theme preferences, why don't we add editor-style syntax highlighting themes here?

Switching to ANSI color codes is probably the way to go; it'd be nice to provide a [256-color palette](http://unix.stackexchange.com/a/124409/181455) since most terminals do or will support it.

Some examples of the kinds of things it'd be cool to support:
- [Sublime Default](https://www.sublimetext.com/)
- [Brackets-Themes/CareBearStareDark](https://github.com/Brackets-Themes/CareBearStareDark)
- [Visual Studio Code](https://code.visualstudio.com/)

The default would probably remain as-is, and use the standard system console colors; color codes should only be written when writing to a terminal so that they don't show up in piped output.

``` csharp
Log.Logger = new LoggerConfiguration()
    .WriteTo.LiterateConsole(theme: LiterateConsoleTheme.VSCode)
    .CreateLogger();
```

`LiterateConsoleTheme` would be a user-constructable class; it may be necessary to make it abstract and provide concrete `SystemLiterateConsoleTheme` and `AnsiLiterateConsoleTheme` or similar.

Needs a more detailed design, but should be approachable.

**Comment by optical** [comment]
@nblumhardt Did you have any thoughts on how we'd do cross platform colour support? From what I can tell, utilizing non-standard colours on Windows requires some P/Invoke trickery, while Unix will need to use ANSI codes. https://github.com/tomakita/Colorful.Console looks like the closest thing there is to a library enabling the use of non-standard colours, but its cross platform support is a little lackluster.

**Comment by nblumhardt** [comment]
@optical I think having an opt-in to ANSI codes at configuration time would be the way to go. On Windows, sticking with the current method by default should be the least disruptive. (Being able to opt-in to ANSI sequences on Windows will mean those running a compatible terminal can decide to use them.) Is this in line with what you're thinking?

**Comment by sm-g** [comment]
I also have unreadable "blue Booleans and null" on Windows 10:
![13-23-04](https://cloud.githubusercontent.com/assets/7280273/25894332/09919096-3584-11e7-8222-692028e33d91.png)

**Comment by nblumhardt** [comment]
#19 covers this.
